## wordpress container.
# wordpress MYSQL database
database:
  build: docker/mysql
  # so that I can access it within 
  # mysqlworkbench on my machine
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=wordpress
    - MYSQL_PASSWORD=wordpress

wordpress:
    links:
    # to access database container
    - database:database
    build: docker/wordpress
    # I dont want to block my port 80 as 
    # I run other containers which are forwarded to port 80
    ports:
       - "8000:80"
    restart: always
    volumes:
      # So that my plugin development in wp-content maps to container wp-content
      - ./wp-content:/var/www/html/wp-content
    environment:
       WORDPRESS_DB_HOST: database:3306
       WORDPRESS_DB_PASSWORD: wordpress
       LOCAL_USER_ID: $UID
       LOCAL_USER_NAME: $USER
